---
name: Validate Changes

on:
  push:
    branches: [main]

  pull_request:
    types: [opened, synchronize]
  
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call_linting_job:
    uses: ./.github/workflows/lint.yml
    
  call_build_job:
    uses: ./.github/workflows/build_project.yml
